#+BEGIN_COMMENT
.. title: P5 Div Shortcode
.. slug: p5-div-shortcode
.. date: 2023-05-05 15:19:31 UTC-07:00
.. tags: p5,template,shortcode
.. category: P5
.. link: 
.. description:A p5 template-based shortcode to add the HTML div to the post. 
.. type: text
.. template: p5.tmpl
#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 3

{{% p5div divid="noise-graph" source="noise_graph.js" %}}

This is a test of the ~p5div~ shortcode. For it to work you need to set up the ~p5.tmpl~ template, have ~..template: p5.tmpl~ in the metadata for this post, and have ~p5div.tmpl~ in a folder named ~shortcodes~ at the root of the nikola folder.

The shortcode used to put the sketch in this post is:

{{% raw %}}
{{% p5div divid="noise-graph" source="noise_graph.js" %}}
{{% /raw %}}

which assumes that the sketch is in ~files/posts/<slug>/noise_graph.js~. And that the p5 code is adding the sketch to "noise-graph". Meaning that there's something like:

#+begin_src js
p5(noise_graph, "noise-graph")
#+end_src

in the ~noise_graph.js~ file.
