#+BEGIN_COMMENT
.. title: Mako P5 HTML Div
.. slug: mako-p5-html-div
.. date: 2023-05-05 16:10:21 UTC-07:00
.. tags: template,mako,,p5
.. category: Mako
.. link: 
.. description: P5 HTML Div shortcode template.
.. type: text
#+END_COMMENT

* The Shortcode Template

This is a shortcode-template to add the HTML for a p5 sketch (the javascript and div tags). Using the shortcode requires two arguments:

 - ~source~: the name of the p5 javascript file (e.g. ~noise_graph.js~)
 - ~divid~ : the ID for the div where the script will be inserted (the second argument passed to the p5 object).

   Let's say we have a p5 sketch saved in a file named ~noise_graph.js~, and we want to put the sketch in a div tag with the ID "noise-graph". Then we would use the shortcode in our post like this.

   {{% raw %}}
   {{ p5div source="noise_graph.js" divid="noise-graph"}}
   {{% /raw %}}

#+begin_src html :tangle p5div.tmpl
<script language="javascript" type="text/javascript" src="${source}"></script>

<div id="${divid}"></div>
#+end_src

Put the ~p5div.tmpl~ file in a folder named ~shortcodes~ next to the ~conf.py~ file (the root of the site).
